### ISSUE TITLE
lint template strings in JS

### ISSUE THREAD

**Issue by graingert** [htmllint/htmllint-cli#21]
I'd like to lint all strings in my JS assigned to the variable `template` or using the template tag `html`

eg:

```js
const template = `
    <div class="foo">
        <span>this is a test</span>
    </div>
`;
```
or

```js
function render(class_) {
    return = html`
        <div class="${class_}">
            <span>this is a test</span>
        </div>
    `;
}
```

**Comment by mlochbaum** [comment]
That sounds hideously complicated to implement. I think your best bet is to either pull those strings out of your html with some hacked-together regex and then put them in files to pass into htmllint, or to get the javascript running in node in order to call htmllint's linter on the constants.

As for supporting it in htmllint, I think I'll have to put a "won't fix" on this one. Sorry.
